#! /bin/bash
printf "%s\n" "$(tput bold)$(date) ${BASH_SOURCE[0]}$(tput sgr0)"

# generated by geo_writer.f08.
#  2020-05-08 12:53:11

# sequence of operations
# 1. bring in geometry file for specific elevation
# 2. run Mercury MoM - pipe into outputs folder
# 3. move Mercury MoM results file to outputs folder
# 4. remove geometry file

# sequence of operations
# 1. bring in geometry file for specific elevation
# 2. run Mercury MoM - pipe into outputs folder
# 3. move Mercury MoM results file to outputs folder
# 4. remove geometry file

# directory structure:

# ./
#   -- bin
#        MMoM_4.1.12
#        elevation-sweep.sh
#   -- inputs
#        facet file
#        geo files
#        materials library (empty file)
#   -- outputs
#        MoM results *.4112.txt
#        MoM run log *.out

# counts steps in batch process
export counter=0
export SECONDS=0
function new_step(){
    export counter=$((counter+1))
    export subcounter=0
    echo ""; echo ""
    echo "Step ${counter}: ${1}"
}
function sub_step(){
    subcounter=$((subcounter+1))
    echo ""
    echo "  Substep ${counter}.${subcounter}: ${1}"
}

# # # shared files
echo 'cp ../inputs/PTW-Materials.lib .'
      cp ../inputs/PTW-Materials.lib .
echo 'cp ../inputs/PTW.facet .'
      cp ../inputs/PTW.facet .

export ticks=${SECONDS}
new_step 'elevation angle = -89 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-89.geo .'
          cp ../inputs/PTW-elev-00-89.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-89.geo > ../outputs/PTW-elev-00-89.out'
          ./MMoM_4.1.12 PTW-elev-00-89.geo > ../outputs/PTW-elev-00-89.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-89.geo'
          rm PTW-elev-00-89.geo

echo ""
echo "time used to run PTW-elev-00-89.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -88 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-88.geo .'
          cp ../inputs/PTW-elev-00-88.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-88.geo > ../outputs/PTW-elev-00-88.out'
          ./MMoM_4.1.12 PTW-elev-00-88.geo > ../outputs/PTW-elev-00-88.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-88.geo'
          rm PTW-elev-00-88.geo

echo ""
echo "time used to run PTW-elev-00-88.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -87 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-87.geo .'
          cp ../inputs/PTW-elev-00-87.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-87.geo > ../outputs/PTW-elev-00-87.out'
          ./MMoM_4.1.12 PTW-elev-00-87.geo > ../outputs/PTW-elev-00-87.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-87.geo'
          rm PTW-elev-00-87.geo

echo ""
echo "time used to run PTW-elev-00-87.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -86 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-86.geo .'
          cp ../inputs/PTW-elev-00-86.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-86.geo > ../outputs/PTW-elev-00-86.out'
          ./MMoM_4.1.12 PTW-elev-00-86.geo > ../outputs/PTW-elev-00-86.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-86.geo'
          rm PTW-elev-00-86.geo

echo ""
echo "time used to run PTW-elev-00-86.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -85 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-85.geo .'
          cp ../inputs/PTW-elev-00-85.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-85.geo > ../outputs/PTW-elev-00-85.out'
          ./MMoM_4.1.12 PTW-elev-00-85.geo > ../outputs/PTW-elev-00-85.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-85.geo'
          rm PTW-elev-00-85.geo

echo ""
echo "time used to run PTW-elev-00-85.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -84 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-84.geo .'
          cp ../inputs/PTW-elev-00-84.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-84.geo > ../outputs/PTW-elev-00-84.out'
          ./MMoM_4.1.12 PTW-elev-00-84.geo > ../outputs/PTW-elev-00-84.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-84.geo'
          rm PTW-elev-00-84.geo

echo ""
echo "time used to run PTW-elev-00-84.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -83 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-83.geo .'
          cp ../inputs/PTW-elev-00-83.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-83.geo > ../outputs/PTW-elev-00-83.out'
          ./MMoM_4.1.12 PTW-elev-00-83.geo > ../outputs/PTW-elev-00-83.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-83.geo'
          rm PTW-elev-00-83.geo

echo ""
echo "time used to run PTW-elev-00-83.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -82 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-82.geo .'
          cp ../inputs/PTW-elev-00-82.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-82.geo > ../outputs/PTW-elev-00-82.out'
          ./MMoM_4.1.12 PTW-elev-00-82.geo > ../outputs/PTW-elev-00-82.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-82.geo'
          rm PTW-elev-00-82.geo

echo ""
echo "time used to run PTW-elev-00-82.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -81 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-81.geo .'
          cp ../inputs/PTW-elev-00-81.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-81.geo > ../outputs/PTW-elev-00-81.out'
          ./MMoM_4.1.12 PTW-elev-00-81.geo > ../outputs/PTW-elev-00-81.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-81.geo'
          rm PTW-elev-00-81.geo

echo ""
echo "time used to run PTW-elev-00-81.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -80 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-80.geo .'
          cp ../inputs/PTW-elev-00-80.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-80.geo > ../outputs/PTW-elev-00-80.out'
          ./MMoM_4.1.12 PTW-elev-00-80.geo > ../outputs/PTW-elev-00-80.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-80.geo'
          rm PTW-elev-00-80.geo

echo ""
echo "time used to run PTW-elev-00-80.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -79 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-79.geo .'
          cp ../inputs/PTW-elev-00-79.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-79.geo > ../outputs/PTW-elev-00-79.out'
          ./MMoM_4.1.12 PTW-elev-00-79.geo > ../outputs/PTW-elev-00-79.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-79.geo'
          rm PTW-elev-00-79.geo

echo ""
echo "time used to run PTW-elev-00-79.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -78 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-78.geo .'
          cp ../inputs/PTW-elev-00-78.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-78.geo > ../outputs/PTW-elev-00-78.out'
          ./MMoM_4.1.12 PTW-elev-00-78.geo > ../outputs/PTW-elev-00-78.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-78.geo'
          rm PTW-elev-00-78.geo

echo ""
echo "time used to run PTW-elev-00-78.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -77 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-77.geo .'
          cp ../inputs/PTW-elev-00-77.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-77.geo > ../outputs/PTW-elev-00-77.out'
          ./MMoM_4.1.12 PTW-elev-00-77.geo > ../outputs/PTW-elev-00-77.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-77.geo'
          rm PTW-elev-00-77.geo

echo ""
echo "time used to run PTW-elev-00-77.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -76 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-76.geo .'
          cp ../inputs/PTW-elev-00-76.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-76.geo > ../outputs/PTW-elev-00-76.out'
          ./MMoM_4.1.12 PTW-elev-00-76.geo > ../outputs/PTW-elev-00-76.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-76.geo'
          rm PTW-elev-00-76.geo

echo ""
echo "time used to run PTW-elev-00-76.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -75 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-75.geo .'
          cp ../inputs/PTW-elev-00-75.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-75.geo > ../outputs/PTW-elev-00-75.out'
          ./MMoM_4.1.12 PTW-elev-00-75.geo > ../outputs/PTW-elev-00-75.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-75.geo'
          rm PTW-elev-00-75.geo

echo ""
echo "time used to run PTW-elev-00-75.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -74 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-74.geo .'
          cp ../inputs/PTW-elev-00-74.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-74.geo > ../outputs/PTW-elev-00-74.out'
          ./MMoM_4.1.12 PTW-elev-00-74.geo > ../outputs/PTW-elev-00-74.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-74.geo'
          rm PTW-elev-00-74.geo

echo ""
echo "time used to run PTW-elev-00-74.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -73 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-73.geo .'
          cp ../inputs/PTW-elev-00-73.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-73.geo > ../outputs/PTW-elev-00-73.out'
          ./MMoM_4.1.12 PTW-elev-00-73.geo > ../outputs/PTW-elev-00-73.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-73.geo'
          rm PTW-elev-00-73.geo

echo ""
echo "time used to run PTW-elev-00-73.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -72 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-72.geo .'
          cp ../inputs/PTW-elev-00-72.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-72.geo > ../outputs/PTW-elev-00-72.out'
          ./MMoM_4.1.12 PTW-elev-00-72.geo > ../outputs/PTW-elev-00-72.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-72.geo'
          rm PTW-elev-00-72.geo

echo ""
echo "time used to run PTW-elev-00-72.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -71 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-71.geo .'
          cp ../inputs/PTW-elev-00-71.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-71.geo > ../outputs/PTW-elev-00-71.out'
          ./MMoM_4.1.12 PTW-elev-00-71.geo > ../outputs/PTW-elev-00-71.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-71.geo'
          rm PTW-elev-00-71.geo

echo ""
echo "time used to run PTW-elev-00-71.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -70 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-70.geo .'
          cp ../inputs/PTW-elev-00-70.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-70.geo > ../outputs/PTW-elev-00-70.out'
          ./MMoM_4.1.12 PTW-elev-00-70.geo > ../outputs/PTW-elev-00-70.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-70.geo'
          rm PTW-elev-00-70.geo

echo ""
echo "time used to run PTW-elev-00-70.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -69 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-69.geo .'
          cp ../inputs/PTW-elev-00-69.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-69.geo > ../outputs/PTW-elev-00-69.out'
          ./MMoM_4.1.12 PTW-elev-00-69.geo > ../outputs/PTW-elev-00-69.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-69.geo'
          rm PTW-elev-00-69.geo

echo ""
echo "time used to run PTW-elev-00-69.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -68 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-68.geo .'
          cp ../inputs/PTW-elev-00-68.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-68.geo > ../outputs/PTW-elev-00-68.out'
          ./MMoM_4.1.12 PTW-elev-00-68.geo > ../outputs/PTW-elev-00-68.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-68.geo'
          rm PTW-elev-00-68.geo

echo ""
echo "time used to run PTW-elev-00-68.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -67 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-67.geo .'
          cp ../inputs/PTW-elev-00-67.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-67.geo > ../outputs/PTW-elev-00-67.out'
          ./MMoM_4.1.12 PTW-elev-00-67.geo > ../outputs/PTW-elev-00-67.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-67.geo'
          rm PTW-elev-00-67.geo

echo ""
echo "time used to run PTW-elev-00-67.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -66 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-66.geo .'
          cp ../inputs/PTW-elev-00-66.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-66.geo > ../outputs/PTW-elev-00-66.out'
          ./MMoM_4.1.12 PTW-elev-00-66.geo > ../outputs/PTW-elev-00-66.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-66.geo'
          rm PTW-elev-00-66.geo

echo ""
echo "time used to run PTW-elev-00-66.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -65 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-65.geo .'
          cp ../inputs/PTW-elev-00-65.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-65.geo > ../outputs/PTW-elev-00-65.out'
          ./MMoM_4.1.12 PTW-elev-00-65.geo > ../outputs/PTW-elev-00-65.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-65.geo'
          rm PTW-elev-00-65.geo

echo ""
echo "time used to run PTW-elev-00-65.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -64 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-64.geo .'
          cp ../inputs/PTW-elev-00-64.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-64.geo > ../outputs/PTW-elev-00-64.out'
          ./MMoM_4.1.12 PTW-elev-00-64.geo > ../outputs/PTW-elev-00-64.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-64.geo'
          rm PTW-elev-00-64.geo

echo ""
echo "time used to run PTW-elev-00-64.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -63 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-63.geo .'
          cp ../inputs/PTW-elev-00-63.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-63.geo > ../outputs/PTW-elev-00-63.out'
          ./MMoM_4.1.12 PTW-elev-00-63.geo > ../outputs/PTW-elev-00-63.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-63.geo'
          rm PTW-elev-00-63.geo

echo ""
echo "time used to run PTW-elev-00-63.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -62 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-62.geo .'
          cp ../inputs/PTW-elev-00-62.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-62.geo > ../outputs/PTW-elev-00-62.out'
          ./MMoM_4.1.12 PTW-elev-00-62.geo > ../outputs/PTW-elev-00-62.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-62.geo'
          rm PTW-elev-00-62.geo

echo ""
echo "time used to run PTW-elev-00-62.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -61 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-61.geo .'
          cp ../inputs/PTW-elev-00-61.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-61.geo > ../outputs/PTW-elev-00-61.out'
          ./MMoM_4.1.12 PTW-elev-00-61.geo > ../outputs/PTW-elev-00-61.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-61.geo'
          rm PTW-elev-00-61.geo

echo ""
echo "time used to run PTW-elev-00-61.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -60 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-60.geo .'
          cp ../inputs/PTW-elev-00-60.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-60.geo > ../outputs/PTW-elev-00-60.out'
          ./MMoM_4.1.12 PTW-elev-00-60.geo > ../outputs/PTW-elev-00-60.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-60.geo'
          rm PTW-elev-00-60.geo

echo ""
echo "time used to run PTW-elev-00-60.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -59 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-59.geo .'
          cp ../inputs/PTW-elev-00-59.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-59.geo > ../outputs/PTW-elev-00-59.out'
          ./MMoM_4.1.12 PTW-elev-00-59.geo > ../outputs/PTW-elev-00-59.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-59.geo'
          rm PTW-elev-00-59.geo

echo ""
echo "time used to run PTW-elev-00-59.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -58 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-58.geo .'
          cp ../inputs/PTW-elev-00-58.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-58.geo > ../outputs/PTW-elev-00-58.out'
          ./MMoM_4.1.12 PTW-elev-00-58.geo > ../outputs/PTW-elev-00-58.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-58.geo'
          rm PTW-elev-00-58.geo

echo ""
echo "time used to run PTW-elev-00-58.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -57 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-57.geo .'
          cp ../inputs/PTW-elev-00-57.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-57.geo > ../outputs/PTW-elev-00-57.out'
          ./MMoM_4.1.12 PTW-elev-00-57.geo > ../outputs/PTW-elev-00-57.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-57.geo'
          rm PTW-elev-00-57.geo

echo ""
echo "time used to run PTW-elev-00-57.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -56 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-56.geo .'
          cp ../inputs/PTW-elev-00-56.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-56.geo > ../outputs/PTW-elev-00-56.out'
          ./MMoM_4.1.12 PTW-elev-00-56.geo > ../outputs/PTW-elev-00-56.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-56.geo'
          rm PTW-elev-00-56.geo

echo ""
echo "time used to run PTW-elev-00-56.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -55 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-55.geo .'
          cp ../inputs/PTW-elev-00-55.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-55.geo > ../outputs/PTW-elev-00-55.out'
          ./MMoM_4.1.12 PTW-elev-00-55.geo > ../outputs/PTW-elev-00-55.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-55.geo'
          rm PTW-elev-00-55.geo

echo ""
echo "time used to run PTW-elev-00-55.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -54 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-54.geo .'
          cp ../inputs/PTW-elev-00-54.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-54.geo > ../outputs/PTW-elev-00-54.out'
          ./MMoM_4.1.12 PTW-elev-00-54.geo > ../outputs/PTW-elev-00-54.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-54.geo'
          rm PTW-elev-00-54.geo

echo ""
echo "time used to run PTW-elev-00-54.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -53 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-53.geo .'
          cp ../inputs/PTW-elev-00-53.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-53.geo > ../outputs/PTW-elev-00-53.out'
          ./MMoM_4.1.12 PTW-elev-00-53.geo > ../outputs/PTW-elev-00-53.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-53.geo'
          rm PTW-elev-00-53.geo

echo ""
echo "time used to run PTW-elev-00-53.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -52 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-52.geo .'
          cp ../inputs/PTW-elev-00-52.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-52.geo > ../outputs/PTW-elev-00-52.out'
          ./MMoM_4.1.12 PTW-elev-00-52.geo > ../outputs/PTW-elev-00-52.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-52.geo'
          rm PTW-elev-00-52.geo

echo ""
echo "time used to run PTW-elev-00-52.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -51 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-51.geo .'
          cp ../inputs/PTW-elev-00-51.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-51.geo > ../outputs/PTW-elev-00-51.out'
          ./MMoM_4.1.12 PTW-elev-00-51.geo > ../outputs/PTW-elev-00-51.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-51.geo'
          rm PTW-elev-00-51.geo

echo ""
echo "time used to run PTW-elev-00-51.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -50 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-50.geo .'
          cp ../inputs/PTW-elev-00-50.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-50.geo > ../outputs/PTW-elev-00-50.out'
          ./MMoM_4.1.12 PTW-elev-00-50.geo > ../outputs/PTW-elev-00-50.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-50.geo'
          rm PTW-elev-00-50.geo

echo ""
echo "time used to run PTW-elev-00-50.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -49 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-49.geo .'
          cp ../inputs/PTW-elev-00-49.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-49.geo > ../outputs/PTW-elev-00-49.out'
          ./MMoM_4.1.12 PTW-elev-00-49.geo > ../outputs/PTW-elev-00-49.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-49.geo'
          rm PTW-elev-00-49.geo

echo ""
echo "time used to run PTW-elev-00-49.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -48 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-48.geo .'
          cp ../inputs/PTW-elev-00-48.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-48.geo > ../outputs/PTW-elev-00-48.out'
          ./MMoM_4.1.12 PTW-elev-00-48.geo > ../outputs/PTW-elev-00-48.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-48.geo'
          rm PTW-elev-00-48.geo

echo ""
echo "time used to run PTW-elev-00-48.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -47 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-47.geo .'
          cp ../inputs/PTW-elev-00-47.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-47.geo > ../outputs/PTW-elev-00-47.out'
          ./MMoM_4.1.12 PTW-elev-00-47.geo > ../outputs/PTW-elev-00-47.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-47.geo'
          rm PTW-elev-00-47.geo

echo ""
echo "time used to run PTW-elev-00-47.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -46 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-46.geo .'
          cp ../inputs/PTW-elev-00-46.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-46.geo > ../outputs/PTW-elev-00-46.out'
          ./MMoM_4.1.12 PTW-elev-00-46.geo > ../outputs/PTW-elev-00-46.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-46.geo'
          rm PTW-elev-00-46.geo

echo ""
echo "time used to run PTW-elev-00-46.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -45 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-45.geo .'
          cp ../inputs/PTW-elev-00-45.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-45.geo > ../outputs/PTW-elev-00-45.out'
          ./MMoM_4.1.12 PTW-elev-00-45.geo > ../outputs/PTW-elev-00-45.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-45.geo'
          rm PTW-elev-00-45.geo

echo ""
echo "time used to run PTW-elev-00-45.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -44 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-44.geo .'
          cp ../inputs/PTW-elev-00-44.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-44.geo > ../outputs/PTW-elev-00-44.out'
          ./MMoM_4.1.12 PTW-elev-00-44.geo > ../outputs/PTW-elev-00-44.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-44.geo'
          rm PTW-elev-00-44.geo

echo ""
echo "time used to run PTW-elev-00-44.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -43 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-43.geo .'
          cp ../inputs/PTW-elev-00-43.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-43.geo > ../outputs/PTW-elev-00-43.out'
          ./MMoM_4.1.12 PTW-elev-00-43.geo > ../outputs/PTW-elev-00-43.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-43.geo'
          rm PTW-elev-00-43.geo

echo ""
echo "time used to run PTW-elev-00-43.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -42 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-42.geo .'
          cp ../inputs/PTW-elev-00-42.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-42.geo > ../outputs/PTW-elev-00-42.out'
          ./MMoM_4.1.12 PTW-elev-00-42.geo > ../outputs/PTW-elev-00-42.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-42.geo'
          rm PTW-elev-00-42.geo

echo ""
echo "time used to run PTW-elev-00-42.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -41 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-41.geo .'
          cp ../inputs/PTW-elev-00-41.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-41.geo > ../outputs/PTW-elev-00-41.out'
          ./MMoM_4.1.12 PTW-elev-00-41.geo > ../outputs/PTW-elev-00-41.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-41.geo'
          rm PTW-elev-00-41.geo

echo ""
echo "time used to run PTW-elev-00-41.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -40 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-40.geo .'
          cp ../inputs/PTW-elev-00-40.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-40.geo > ../outputs/PTW-elev-00-40.out'
          ./MMoM_4.1.12 PTW-elev-00-40.geo > ../outputs/PTW-elev-00-40.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-40.geo'
          rm PTW-elev-00-40.geo

echo ""
echo "time used to run PTW-elev-00-40.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -39 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-39.geo .'
          cp ../inputs/PTW-elev-00-39.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-39.geo > ../outputs/PTW-elev-00-39.out'
          ./MMoM_4.1.12 PTW-elev-00-39.geo > ../outputs/PTW-elev-00-39.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-39.geo'
          rm PTW-elev-00-39.geo

echo ""
echo "time used to run PTW-elev-00-39.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -38 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-38.geo .'
          cp ../inputs/PTW-elev-00-38.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-38.geo > ../outputs/PTW-elev-00-38.out'
          ./MMoM_4.1.12 PTW-elev-00-38.geo > ../outputs/PTW-elev-00-38.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-38.geo'
          rm PTW-elev-00-38.geo

echo ""
echo "time used to run PTW-elev-00-38.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -37 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-37.geo .'
          cp ../inputs/PTW-elev-00-37.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-37.geo > ../outputs/PTW-elev-00-37.out'
          ./MMoM_4.1.12 PTW-elev-00-37.geo > ../outputs/PTW-elev-00-37.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-37.geo'
          rm PTW-elev-00-37.geo

echo ""
echo "time used to run PTW-elev-00-37.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -36 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-36.geo .'
          cp ../inputs/PTW-elev-00-36.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-36.geo > ../outputs/PTW-elev-00-36.out'
          ./MMoM_4.1.12 PTW-elev-00-36.geo > ../outputs/PTW-elev-00-36.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-36.geo'
          rm PTW-elev-00-36.geo

echo ""
echo "time used to run PTW-elev-00-36.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -35 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-35.geo .'
          cp ../inputs/PTW-elev-00-35.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-35.geo > ../outputs/PTW-elev-00-35.out'
          ./MMoM_4.1.12 PTW-elev-00-35.geo > ../outputs/PTW-elev-00-35.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-35.geo'
          rm PTW-elev-00-35.geo

echo ""
echo "time used to run PTW-elev-00-35.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -34 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-34.geo .'
          cp ../inputs/PTW-elev-00-34.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-34.geo > ../outputs/PTW-elev-00-34.out'
          ./MMoM_4.1.12 PTW-elev-00-34.geo > ../outputs/PTW-elev-00-34.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-34.geo'
          rm PTW-elev-00-34.geo

echo ""
echo "time used to run PTW-elev-00-34.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -33 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-33.geo .'
          cp ../inputs/PTW-elev-00-33.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-33.geo > ../outputs/PTW-elev-00-33.out'
          ./MMoM_4.1.12 PTW-elev-00-33.geo > ../outputs/PTW-elev-00-33.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-33.geo'
          rm PTW-elev-00-33.geo

echo ""
echo "time used to run PTW-elev-00-33.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -32 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-32.geo .'
          cp ../inputs/PTW-elev-00-32.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-32.geo > ../outputs/PTW-elev-00-32.out'
          ./MMoM_4.1.12 PTW-elev-00-32.geo > ../outputs/PTW-elev-00-32.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-32.geo'
          rm PTW-elev-00-32.geo

echo ""
echo "time used to run PTW-elev-00-32.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -31 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-31.geo .'
          cp ../inputs/PTW-elev-00-31.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-31.geo > ../outputs/PTW-elev-00-31.out'
          ./MMoM_4.1.12 PTW-elev-00-31.geo > ../outputs/PTW-elev-00-31.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-31.geo'
          rm PTW-elev-00-31.geo

echo ""
echo "time used to run PTW-elev-00-31.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -30 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-30.geo .'
          cp ../inputs/PTW-elev-00-30.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-30.geo > ../outputs/PTW-elev-00-30.out'
          ./MMoM_4.1.12 PTW-elev-00-30.geo > ../outputs/PTW-elev-00-30.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-30.geo'
          rm PTW-elev-00-30.geo

echo ""
echo "time used to run PTW-elev-00-30.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -29 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-29.geo .'
          cp ../inputs/PTW-elev-00-29.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-29.geo > ../outputs/PTW-elev-00-29.out'
          ./MMoM_4.1.12 PTW-elev-00-29.geo > ../outputs/PTW-elev-00-29.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-29.geo'
          rm PTW-elev-00-29.geo

echo ""
echo "time used to run PTW-elev-00-29.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -28 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-28.geo .'
          cp ../inputs/PTW-elev-00-28.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-28.geo > ../outputs/PTW-elev-00-28.out'
          ./MMoM_4.1.12 PTW-elev-00-28.geo > ../outputs/PTW-elev-00-28.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-28.geo'
          rm PTW-elev-00-28.geo

echo ""
echo "time used to run PTW-elev-00-28.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -27 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-27.geo .'
          cp ../inputs/PTW-elev-00-27.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-27.geo > ../outputs/PTW-elev-00-27.out'
          ./MMoM_4.1.12 PTW-elev-00-27.geo > ../outputs/PTW-elev-00-27.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-27.geo'
          rm PTW-elev-00-27.geo

echo ""
echo "time used to run PTW-elev-00-27.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -26 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-26.geo .'
          cp ../inputs/PTW-elev-00-26.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-26.geo > ../outputs/PTW-elev-00-26.out'
          ./MMoM_4.1.12 PTW-elev-00-26.geo > ../outputs/PTW-elev-00-26.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-26.geo'
          rm PTW-elev-00-26.geo

echo ""
echo "time used to run PTW-elev-00-26.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -25 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-25.geo .'
          cp ../inputs/PTW-elev-00-25.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-25.geo > ../outputs/PTW-elev-00-25.out'
          ./MMoM_4.1.12 PTW-elev-00-25.geo > ../outputs/PTW-elev-00-25.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-25.geo'
          rm PTW-elev-00-25.geo

echo ""
echo "time used to run PTW-elev-00-25.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -24 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-24.geo .'
          cp ../inputs/PTW-elev-00-24.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-24.geo > ../outputs/PTW-elev-00-24.out'
          ./MMoM_4.1.12 PTW-elev-00-24.geo > ../outputs/PTW-elev-00-24.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-24.geo'
          rm PTW-elev-00-24.geo

echo ""
echo "time used to run PTW-elev-00-24.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -23 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-23.geo .'
          cp ../inputs/PTW-elev-00-23.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-23.geo > ../outputs/PTW-elev-00-23.out'
          ./MMoM_4.1.12 PTW-elev-00-23.geo > ../outputs/PTW-elev-00-23.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-23.geo'
          rm PTW-elev-00-23.geo

echo ""
echo "time used to run PTW-elev-00-23.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -22 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-22.geo .'
          cp ../inputs/PTW-elev-00-22.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-22.geo > ../outputs/PTW-elev-00-22.out'
          ./MMoM_4.1.12 PTW-elev-00-22.geo > ../outputs/PTW-elev-00-22.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-22.geo'
          rm PTW-elev-00-22.geo

echo ""
echo "time used to run PTW-elev-00-22.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -21 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-21.geo .'
          cp ../inputs/PTW-elev-00-21.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-21.geo > ../outputs/PTW-elev-00-21.out'
          ./MMoM_4.1.12 PTW-elev-00-21.geo > ../outputs/PTW-elev-00-21.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-21.geo'
          rm PTW-elev-00-21.geo

echo ""
echo "time used to run PTW-elev-00-21.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -20 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-20.geo .'
          cp ../inputs/PTW-elev-00-20.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-20.geo > ../outputs/PTW-elev-00-20.out'
          ./MMoM_4.1.12 PTW-elev-00-20.geo > ../outputs/PTW-elev-00-20.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-20.geo'
          rm PTW-elev-00-20.geo

echo ""
echo "time used to run PTW-elev-00-20.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -19 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-19.geo .'
          cp ../inputs/PTW-elev-00-19.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-19.geo > ../outputs/PTW-elev-00-19.out'
          ./MMoM_4.1.12 PTW-elev-00-19.geo > ../outputs/PTW-elev-00-19.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-19.geo'
          rm PTW-elev-00-19.geo

echo ""
echo "time used to run PTW-elev-00-19.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -18 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-18.geo .'
          cp ../inputs/PTW-elev-00-18.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-18.geo > ../outputs/PTW-elev-00-18.out'
          ./MMoM_4.1.12 PTW-elev-00-18.geo > ../outputs/PTW-elev-00-18.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-18.geo'
          rm PTW-elev-00-18.geo

echo ""
echo "time used to run PTW-elev-00-18.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -17 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-17.geo .'
          cp ../inputs/PTW-elev-00-17.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-17.geo > ../outputs/PTW-elev-00-17.out'
          ./MMoM_4.1.12 PTW-elev-00-17.geo > ../outputs/PTW-elev-00-17.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-17.geo'
          rm PTW-elev-00-17.geo

echo ""
echo "time used to run PTW-elev-00-17.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -16 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-16.geo .'
          cp ../inputs/PTW-elev-00-16.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-16.geo > ../outputs/PTW-elev-00-16.out'
          ./MMoM_4.1.12 PTW-elev-00-16.geo > ../outputs/PTW-elev-00-16.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-16.geo'
          rm PTW-elev-00-16.geo

echo ""
echo "time used to run PTW-elev-00-16.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -15 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-15.geo .'
          cp ../inputs/PTW-elev-00-15.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-15.geo > ../outputs/PTW-elev-00-15.out'
          ./MMoM_4.1.12 PTW-elev-00-15.geo > ../outputs/PTW-elev-00-15.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-15.geo'
          rm PTW-elev-00-15.geo

echo ""
echo "time used to run PTW-elev-00-15.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -14 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-14.geo .'
          cp ../inputs/PTW-elev-00-14.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-14.geo > ../outputs/PTW-elev-00-14.out'
          ./MMoM_4.1.12 PTW-elev-00-14.geo > ../outputs/PTW-elev-00-14.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-14.geo'
          rm PTW-elev-00-14.geo

echo ""
echo "time used to run PTW-elev-00-14.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -13 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-13.geo .'
          cp ../inputs/PTW-elev-00-13.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-13.geo > ../outputs/PTW-elev-00-13.out'
          ./MMoM_4.1.12 PTW-elev-00-13.geo > ../outputs/PTW-elev-00-13.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-13.geo'
          rm PTW-elev-00-13.geo

echo ""
echo "time used to run PTW-elev-00-13.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -12 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-12.geo .'
          cp ../inputs/PTW-elev-00-12.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-12.geo > ../outputs/PTW-elev-00-12.out'
          ./MMoM_4.1.12 PTW-elev-00-12.geo > ../outputs/PTW-elev-00-12.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-12.geo'
          rm PTW-elev-00-12.geo

echo ""
echo "time used to run PTW-elev-00-12.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -11 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-11.geo .'
          cp ../inputs/PTW-elev-00-11.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-11.geo > ../outputs/PTW-elev-00-11.out'
          ./MMoM_4.1.12 PTW-elev-00-11.geo > ../outputs/PTW-elev-00-11.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-11.geo'
          rm PTW-elev-00-11.geo

echo ""
echo "time used to run PTW-elev-00-11.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -10 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00-10.geo .'
          cp ../inputs/PTW-elev-00-10.geo .

sub_step './MMoM_4.1.12 PTW-elev-00-10.geo > ../outputs/PTW-elev-00-10.out'
          ./MMoM_4.1.12 PTW-elev-00-10.geo > ../outputs/PTW-elev-00-10.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00-10.geo'
          rm PTW-elev-00-10.geo

echo ""
echo "time used to run PTW-elev-00-10.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -9 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-000-9.geo .'
          cp ../inputs/PTW-elev-000-9.geo .

sub_step './MMoM_4.1.12 PTW-elev-000-9.geo > ../outputs/PTW-elev-000-9.out'
          ./MMoM_4.1.12 PTW-elev-000-9.geo > ../outputs/PTW-elev-000-9.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-000-9.geo'
          rm PTW-elev-000-9.geo

echo ""
echo "time used to run PTW-elev-000-9.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -8 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-000-8.geo .'
          cp ../inputs/PTW-elev-000-8.geo .

sub_step './MMoM_4.1.12 PTW-elev-000-8.geo > ../outputs/PTW-elev-000-8.out'
          ./MMoM_4.1.12 PTW-elev-000-8.geo > ../outputs/PTW-elev-000-8.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-000-8.geo'
          rm PTW-elev-000-8.geo

echo ""
echo "time used to run PTW-elev-000-8.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -7 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-000-7.geo .'
          cp ../inputs/PTW-elev-000-7.geo .

sub_step './MMoM_4.1.12 PTW-elev-000-7.geo > ../outputs/PTW-elev-000-7.out'
          ./MMoM_4.1.12 PTW-elev-000-7.geo > ../outputs/PTW-elev-000-7.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-000-7.geo'
          rm PTW-elev-000-7.geo

echo ""
echo "time used to run PTW-elev-000-7.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -6 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-000-6.geo .'
          cp ../inputs/PTW-elev-000-6.geo .

sub_step './MMoM_4.1.12 PTW-elev-000-6.geo > ../outputs/PTW-elev-000-6.out'
          ./MMoM_4.1.12 PTW-elev-000-6.geo > ../outputs/PTW-elev-000-6.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-000-6.geo'
          rm PTW-elev-000-6.geo

echo ""
echo "time used to run PTW-elev-000-6.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -5 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-000-5.geo .'
          cp ../inputs/PTW-elev-000-5.geo .

sub_step './MMoM_4.1.12 PTW-elev-000-5.geo > ../outputs/PTW-elev-000-5.out'
          ./MMoM_4.1.12 PTW-elev-000-5.geo > ../outputs/PTW-elev-000-5.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-000-5.geo'
          rm PTW-elev-000-5.geo

echo ""
echo "time used to run PTW-elev-000-5.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -4 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-000-4.geo .'
          cp ../inputs/PTW-elev-000-4.geo .

sub_step './MMoM_4.1.12 PTW-elev-000-4.geo > ../outputs/PTW-elev-000-4.out'
          ./MMoM_4.1.12 PTW-elev-000-4.geo > ../outputs/PTW-elev-000-4.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-000-4.geo'
          rm PTW-elev-000-4.geo

echo ""
echo "time used to run PTW-elev-000-4.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -3 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-000-3.geo .'
          cp ../inputs/PTW-elev-000-3.geo .

sub_step './MMoM_4.1.12 PTW-elev-000-3.geo > ../outputs/PTW-elev-000-3.out'
          ./MMoM_4.1.12 PTW-elev-000-3.geo > ../outputs/PTW-elev-000-3.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-000-3.geo'
          rm PTW-elev-000-3.geo

echo ""
echo "time used to run PTW-elev-000-3.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -2 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-000-2.geo .'
          cp ../inputs/PTW-elev-000-2.geo .

sub_step './MMoM_4.1.12 PTW-elev-000-2.geo > ../outputs/PTW-elev-000-2.out'
          ./MMoM_4.1.12 PTW-elev-000-2.geo > ../outputs/PTW-elev-000-2.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-000-2.geo'
          rm PTW-elev-000-2.geo

echo ""
echo "time used to run PTW-elev-000-2.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = -1 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-000-1.geo .'
          cp ../inputs/PTW-elev-000-1.geo .

sub_step './MMoM_4.1.12 PTW-elev-000-1.geo > ../outputs/PTW-elev-000-1.out'
          ./MMoM_4.1.12 PTW-elev-000-1.geo > ../outputs/PTW-elev-000-1.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-000-1.geo'
          rm PTW-elev-000-1.geo

echo ""
echo "time used to run PTW-elev-000-1.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 0 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00000.geo .'
          cp ../inputs/PTW-elev-00000.geo .

sub_step './MMoM_4.1.12 PTW-elev-00000.geo > ../outputs/PTW-elev-00000.out'
          ./MMoM_4.1.12 PTW-elev-00000.geo > ../outputs/PTW-elev-00000.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00000.geo'
          rm PTW-elev-00000.geo

echo ""
echo "time used to run PTW-elev-00000.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 1 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00001.geo .'
          cp ../inputs/PTW-elev-00001.geo .

sub_step './MMoM_4.1.12 PTW-elev-00001.geo > ../outputs/PTW-elev-00001.out'
          ./MMoM_4.1.12 PTW-elev-00001.geo > ../outputs/PTW-elev-00001.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00001.geo'
          rm PTW-elev-00001.geo

echo ""
echo "time used to run PTW-elev-00001.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 2 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00002.geo .'
          cp ../inputs/PTW-elev-00002.geo .

sub_step './MMoM_4.1.12 PTW-elev-00002.geo > ../outputs/PTW-elev-00002.out'
          ./MMoM_4.1.12 PTW-elev-00002.geo > ../outputs/PTW-elev-00002.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00002.geo'
          rm PTW-elev-00002.geo

echo ""
echo "time used to run PTW-elev-00002.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 3 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00003.geo .'
          cp ../inputs/PTW-elev-00003.geo .

sub_step './MMoM_4.1.12 PTW-elev-00003.geo > ../outputs/PTW-elev-00003.out'
          ./MMoM_4.1.12 PTW-elev-00003.geo > ../outputs/PTW-elev-00003.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00003.geo'
          rm PTW-elev-00003.geo

echo ""
echo "time used to run PTW-elev-00003.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 4 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00004.geo .'
          cp ../inputs/PTW-elev-00004.geo .

sub_step './MMoM_4.1.12 PTW-elev-00004.geo > ../outputs/PTW-elev-00004.out'
          ./MMoM_4.1.12 PTW-elev-00004.geo > ../outputs/PTW-elev-00004.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00004.geo'
          rm PTW-elev-00004.geo

echo ""
echo "time used to run PTW-elev-00004.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 5 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00005.geo .'
          cp ../inputs/PTW-elev-00005.geo .

sub_step './MMoM_4.1.12 PTW-elev-00005.geo > ../outputs/PTW-elev-00005.out'
          ./MMoM_4.1.12 PTW-elev-00005.geo > ../outputs/PTW-elev-00005.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00005.geo'
          rm PTW-elev-00005.geo

echo ""
echo "time used to run PTW-elev-00005.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 6 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00006.geo .'
          cp ../inputs/PTW-elev-00006.geo .

sub_step './MMoM_4.1.12 PTW-elev-00006.geo > ../outputs/PTW-elev-00006.out'
          ./MMoM_4.1.12 PTW-elev-00006.geo > ../outputs/PTW-elev-00006.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00006.geo'
          rm PTW-elev-00006.geo

echo ""
echo "time used to run PTW-elev-00006.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 7 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00007.geo .'
          cp ../inputs/PTW-elev-00007.geo .

sub_step './MMoM_4.1.12 PTW-elev-00007.geo > ../outputs/PTW-elev-00007.out'
          ./MMoM_4.1.12 PTW-elev-00007.geo > ../outputs/PTW-elev-00007.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00007.geo'
          rm PTW-elev-00007.geo

echo ""
echo "time used to run PTW-elev-00007.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 8 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00008.geo .'
          cp ../inputs/PTW-elev-00008.geo .

sub_step './MMoM_4.1.12 PTW-elev-00008.geo > ../outputs/PTW-elev-00008.out'
          ./MMoM_4.1.12 PTW-elev-00008.geo > ../outputs/PTW-elev-00008.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00008.geo'
          rm PTW-elev-00008.geo

echo ""
echo "time used to run PTW-elev-00008.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 9 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00009.geo .'
          cp ../inputs/PTW-elev-00009.geo .

sub_step './MMoM_4.1.12 PTW-elev-00009.geo > ../outputs/PTW-elev-00009.out'
          ./MMoM_4.1.12 PTW-elev-00009.geo > ../outputs/PTW-elev-00009.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00009.geo'
          rm PTW-elev-00009.geo

echo ""
echo "time used to run PTW-elev-00009.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 10 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00010.geo .'
          cp ../inputs/PTW-elev-00010.geo .

sub_step './MMoM_4.1.12 PTW-elev-00010.geo > ../outputs/PTW-elev-00010.out'
          ./MMoM_4.1.12 PTW-elev-00010.geo > ../outputs/PTW-elev-00010.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00010.geo'
          rm PTW-elev-00010.geo

echo ""
echo "time used to run PTW-elev-00010.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 11 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00011.geo .'
          cp ../inputs/PTW-elev-00011.geo .

sub_step './MMoM_4.1.12 PTW-elev-00011.geo > ../outputs/PTW-elev-00011.out'
          ./MMoM_4.1.12 PTW-elev-00011.geo > ../outputs/PTW-elev-00011.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00011.geo'
          rm PTW-elev-00011.geo

echo ""
echo "time used to run PTW-elev-00011.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 12 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00012.geo .'
          cp ../inputs/PTW-elev-00012.geo .

sub_step './MMoM_4.1.12 PTW-elev-00012.geo > ../outputs/PTW-elev-00012.out'
          ./MMoM_4.1.12 PTW-elev-00012.geo > ../outputs/PTW-elev-00012.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00012.geo'
          rm PTW-elev-00012.geo

echo ""
echo "time used to run PTW-elev-00012.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 13 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00013.geo .'
          cp ../inputs/PTW-elev-00013.geo .

sub_step './MMoM_4.1.12 PTW-elev-00013.geo > ../outputs/PTW-elev-00013.out'
          ./MMoM_4.1.12 PTW-elev-00013.geo > ../outputs/PTW-elev-00013.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00013.geo'
          rm PTW-elev-00013.geo

echo ""
echo "time used to run PTW-elev-00013.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 14 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00014.geo .'
          cp ../inputs/PTW-elev-00014.geo .

sub_step './MMoM_4.1.12 PTW-elev-00014.geo > ../outputs/PTW-elev-00014.out'
          ./MMoM_4.1.12 PTW-elev-00014.geo > ../outputs/PTW-elev-00014.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00014.geo'
          rm PTW-elev-00014.geo

echo ""
echo "time used to run PTW-elev-00014.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 15 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00015.geo .'
          cp ../inputs/PTW-elev-00015.geo .

sub_step './MMoM_4.1.12 PTW-elev-00015.geo > ../outputs/PTW-elev-00015.out'
          ./MMoM_4.1.12 PTW-elev-00015.geo > ../outputs/PTW-elev-00015.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00015.geo'
          rm PTW-elev-00015.geo

echo ""
echo "time used to run PTW-elev-00015.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 16 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00016.geo .'
          cp ../inputs/PTW-elev-00016.geo .

sub_step './MMoM_4.1.12 PTW-elev-00016.geo > ../outputs/PTW-elev-00016.out'
          ./MMoM_4.1.12 PTW-elev-00016.geo > ../outputs/PTW-elev-00016.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00016.geo'
          rm PTW-elev-00016.geo

echo ""
echo "time used to run PTW-elev-00016.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 17 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00017.geo .'
          cp ../inputs/PTW-elev-00017.geo .

sub_step './MMoM_4.1.12 PTW-elev-00017.geo > ../outputs/PTW-elev-00017.out'
          ./MMoM_4.1.12 PTW-elev-00017.geo > ../outputs/PTW-elev-00017.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00017.geo'
          rm PTW-elev-00017.geo

echo ""
echo "time used to run PTW-elev-00017.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 18 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00018.geo .'
          cp ../inputs/PTW-elev-00018.geo .

sub_step './MMoM_4.1.12 PTW-elev-00018.geo > ../outputs/PTW-elev-00018.out'
          ./MMoM_4.1.12 PTW-elev-00018.geo > ../outputs/PTW-elev-00018.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00018.geo'
          rm PTW-elev-00018.geo

echo ""
echo "time used to run PTW-elev-00018.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 19 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00019.geo .'
          cp ../inputs/PTW-elev-00019.geo .

sub_step './MMoM_4.1.12 PTW-elev-00019.geo > ../outputs/PTW-elev-00019.out'
          ./MMoM_4.1.12 PTW-elev-00019.geo > ../outputs/PTW-elev-00019.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00019.geo'
          rm PTW-elev-00019.geo

echo ""
echo "time used to run PTW-elev-00019.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 20 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00020.geo .'
          cp ../inputs/PTW-elev-00020.geo .

sub_step './MMoM_4.1.12 PTW-elev-00020.geo > ../outputs/PTW-elev-00020.out'
          ./MMoM_4.1.12 PTW-elev-00020.geo > ../outputs/PTW-elev-00020.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00020.geo'
          rm PTW-elev-00020.geo

echo ""
echo "time used to run PTW-elev-00020.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 21 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00021.geo .'
          cp ../inputs/PTW-elev-00021.geo .

sub_step './MMoM_4.1.12 PTW-elev-00021.geo > ../outputs/PTW-elev-00021.out'
          ./MMoM_4.1.12 PTW-elev-00021.geo > ../outputs/PTW-elev-00021.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00021.geo'
          rm PTW-elev-00021.geo

echo ""
echo "time used to run PTW-elev-00021.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 22 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00022.geo .'
          cp ../inputs/PTW-elev-00022.geo .

sub_step './MMoM_4.1.12 PTW-elev-00022.geo > ../outputs/PTW-elev-00022.out'
          ./MMoM_4.1.12 PTW-elev-00022.geo > ../outputs/PTW-elev-00022.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00022.geo'
          rm PTW-elev-00022.geo

echo ""
echo "time used to run PTW-elev-00022.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 23 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00023.geo .'
          cp ../inputs/PTW-elev-00023.geo .

sub_step './MMoM_4.1.12 PTW-elev-00023.geo > ../outputs/PTW-elev-00023.out'
          ./MMoM_4.1.12 PTW-elev-00023.geo > ../outputs/PTW-elev-00023.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00023.geo'
          rm PTW-elev-00023.geo

echo ""
echo "time used to run PTW-elev-00023.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 24 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00024.geo .'
          cp ../inputs/PTW-elev-00024.geo .

sub_step './MMoM_4.1.12 PTW-elev-00024.geo > ../outputs/PTW-elev-00024.out'
          ./MMoM_4.1.12 PTW-elev-00024.geo > ../outputs/PTW-elev-00024.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00024.geo'
          rm PTW-elev-00024.geo

echo ""
echo "time used to run PTW-elev-00024.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 25 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00025.geo .'
          cp ../inputs/PTW-elev-00025.geo .

sub_step './MMoM_4.1.12 PTW-elev-00025.geo > ../outputs/PTW-elev-00025.out'
          ./MMoM_4.1.12 PTW-elev-00025.geo > ../outputs/PTW-elev-00025.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00025.geo'
          rm PTW-elev-00025.geo

echo ""
echo "time used to run PTW-elev-00025.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 26 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00026.geo .'
          cp ../inputs/PTW-elev-00026.geo .

sub_step './MMoM_4.1.12 PTW-elev-00026.geo > ../outputs/PTW-elev-00026.out'
          ./MMoM_4.1.12 PTW-elev-00026.geo > ../outputs/PTW-elev-00026.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00026.geo'
          rm PTW-elev-00026.geo

echo ""
echo "time used to run PTW-elev-00026.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 27 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00027.geo .'
          cp ../inputs/PTW-elev-00027.geo .

sub_step './MMoM_4.1.12 PTW-elev-00027.geo > ../outputs/PTW-elev-00027.out'
          ./MMoM_4.1.12 PTW-elev-00027.geo > ../outputs/PTW-elev-00027.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00027.geo'
          rm PTW-elev-00027.geo

echo ""
echo "time used to run PTW-elev-00027.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 28 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00028.geo .'
          cp ../inputs/PTW-elev-00028.geo .

sub_step './MMoM_4.1.12 PTW-elev-00028.geo > ../outputs/PTW-elev-00028.out'
          ./MMoM_4.1.12 PTW-elev-00028.geo > ../outputs/PTW-elev-00028.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00028.geo'
          rm PTW-elev-00028.geo

echo ""
echo "time used to run PTW-elev-00028.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 29 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00029.geo .'
          cp ../inputs/PTW-elev-00029.geo .

sub_step './MMoM_4.1.12 PTW-elev-00029.geo > ../outputs/PTW-elev-00029.out'
          ./MMoM_4.1.12 PTW-elev-00029.geo > ../outputs/PTW-elev-00029.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00029.geo'
          rm PTW-elev-00029.geo

echo ""
echo "time used to run PTW-elev-00029.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 30 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00030.geo .'
          cp ../inputs/PTW-elev-00030.geo .

sub_step './MMoM_4.1.12 PTW-elev-00030.geo > ../outputs/PTW-elev-00030.out'
          ./MMoM_4.1.12 PTW-elev-00030.geo > ../outputs/PTW-elev-00030.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00030.geo'
          rm PTW-elev-00030.geo

echo ""
echo "time used to run PTW-elev-00030.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 31 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00031.geo .'
          cp ../inputs/PTW-elev-00031.geo .

sub_step './MMoM_4.1.12 PTW-elev-00031.geo > ../outputs/PTW-elev-00031.out'
          ./MMoM_4.1.12 PTW-elev-00031.geo > ../outputs/PTW-elev-00031.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00031.geo'
          rm PTW-elev-00031.geo

echo ""
echo "time used to run PTW-elev-00031.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 32 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00032.geo .'
          cp ../inputs/PTW-elev-00032.geo .

sub_step './MMoM_4.1.12 PTW-elev-00032.geo > ../outputs/PTW-elev-00032.out'
          ./MMoM_4.1.12 PTW-elev-00032.geo > ../outputs/PTW-elev-00032.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00032.geo'
          rm PTW-elev-00032.geo

echo ""
echo "time used to run PTW-elev-00032.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 33 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00033.geo .'
          cp ../inputs/PTW-elev-00033.geo .

sub_step './MMoM_4.1.12 PTW-elev-00033.geo > ../outputs/PTW-elev-00033.out'
          ./MMoM_4.1.12 PTW-elev-00033.geo > ../outputs/PTW-elev-00033.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00033.geo'
          rm PTW-elev-00033.geo

echo ""
echo "time used to run PTW-elev-00033.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 34 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00034.geo .'
          cp ../inputs/PTW-elev-00034.geo .

sub_step './MMoM_4.1.12 PTW-elev-00034.geo > ../outputs/PTW-elev-00034.out'
          ./MMoM_4.1.12 PTW-elev-00034.geo > ../outputs/PTW-elev-00034.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00034.geo'
          rm PTW-elev-00034.geo

echo ""
echo "time used to run PTW-elev-00034.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 35 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00035.geo .'
          cp ../inputs/PTW-elev-00035.geo .

sub_step './MMoM_4.1.12 PTW-elev-00035.geo > ../outputs/PTW-elev-00035.out'
          ./MMoM_4.1.12 PTW-elev-00035.geo > ../outputs/PTW-elev-00035.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00035.geo'
          rm PTW-elev-00035.geo

echo ""
echo "time used to run PTW-elev-00035.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 36 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00036.geo .'
          cp ../inputs/PTW-elev-00036.geo .

sub_step './MMoM_4.1.12 PTW-elev-00036.geo > ../outputs/PTW-elev-00036.out'
          ./MMoM_4.1.12 PTW-elev-00036.geo > ../outputs/PTW-elev-00036.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00036.geo'
          rm PTW-elev-00036.geo

echo ""
echo "time used to run PTW-elev-00036.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 37 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00037.geo .'
          cp ../inputs/PTW-elev-00037.geo .

sub_step './MMoM_4.1.12 PTW-elev-00037.geo > ../outputs/PTW-elev-00037.out'
          ./MMoM_4.1.12 PTW-elev-00037.geo > ../outputs/PTW-elev-00037.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00037.geo'
          rm PTW-elev-00037.geo

echo ""
echo "time used to run PTW-elev-00037.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 38 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00038.geo .'
          cp ../inputs/PTW-elev-00038.geo .

sub_step './MMoM_4.1.12 PTW-elev-00038.geo > ../outputs/PTW-elev-00038.out'
          ./MMoM_4.1.12 PTW-elev-00038.geo > ../outputs/PTW-elev-00038.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00038.geo'
          rm PTW-elev-00038.geo

echo ""
echo "time used to run PTW-elev-00038.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 39 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00039.geo .'
          cp ../inputs/PTW-elev-00039.geo .

sub_step './MMoM_4.1.12 PTW-elev-00039.geo > ../outputs/PTW-elev-00039.out'
          ./MMoM_4.1.12 PTW-elev-00039.geo > ../outputs/PTW-elev-00039.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00039.geo'
          rm PTW-elev-00039.geo

echo ""
echo "time used to run PTW-elev-00039.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 40 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00040.geo .'
          cp ../inputs/PTW-elev-00040.geo .

sub_step './MMoM_4.1.12 PTW-elev-00040.geo > ../outputs/PTW-elev-00040.out'
          ./MMoM_4.1.12 PTW-elev-00040.geo > ../outputs/PTW-elev-00040.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00040.geo'
          rm PTW-elev-00040.geo

echo ""
echo "time used to run PTW-elev-00040.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 41 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00041.geo .'
          cp ../inputs/PTW-elev-00041.geo .

sub_step './MMoM_4.1.12 PTW-elev-00041.geo > ../outputs/PTW-elev-00041.out'
          ./MMoM_4.1.12 PTW-elev-00041.geo > ../outputs/PTW-elev-00041.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00041.geo'
          rm PTW-elev-00041.geo

echo ""
echo "time used to run PTW-elev-00041.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 42 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00042.geo .'
          cp ../inputs/PTW-elev-00042.geo .

sub_step './MMoM_4.1.12 PTW-elev-00042.geo > ../outputs/PTW-elev-00042.out'
          ./MMoM_4.1.12 PTW-elev-00042.geo > ../outputs/PTW-elev-00042.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00042.geo'
          rm PTW-elev-00042.geo

echo ""
echo "time used to run PTW-elev-00042.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 43 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00043.geo .'
          cp ../inputs/PTW-elev-00043.geo .

sub_step './MMoM_4.1.12 PTW-elev-00043.geo > ../outputs/PTW-elev-00043.out'
          ./MMoM_4.1.12 PTW-elev-00043.geo > ../outputs/PTW-elev-00043.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00043.geo'
          rm PTW-elev-00043.geo

echo ""
echo "time used to run PTW-elev-00043.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 44 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00044.geo .'
          cp ../inputs/PTW-elev-00044.geo .

sub_step './MMoM_4.1.12 PTW-elev-00044.geo > ../outputs/PTW-elev-00044.out'
          ./MMoM_4.1.12 PTW-elev-00044.geo > ../outputs/PTW-elev-00044.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00044.geo'
          rm PTW-elev-00044.geo

echo ""
echo "time used to run PTW-elev-00044.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 45 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00045.geo .'
          cp ../inputs/PTW-elev-00045.geo .

sub_step './MMoM_4.1.12 PTW-elev-00045.geo > ../outputs/PTW-elev-00045.out'
          ./MMoM_4.1.12 PTW-elev-00045.geo > ../outputs/PTW-elev-00045.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00045.geo'
          rm PTW-elev-00045.geo

echo ""
echo "time used to run PTW-elev-00045.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 46 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00046.geo .'
          cp ../inputs/PTW-elev-00046.geo .

sub_step './MMoM_4.1.12 PTW-elev-00046.geo > ../outputs/PTW-elev-00046.out'
          ./MMoM_4.1.12 PTW-elev-00046.geo > ../outputs/PTW-elev-00046.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00046.geo'
          rm PTW-elev-00046.geo

echo ""
echo "time used to run PTW-elev-00046.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 47 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00047.geo .'
          cp ../inputs/PTW-elev-00047.geo .

sub_step './MMoM_4.1.12 PTW-elev-00047.geo > ../outputs/PTW-elev-00047.out'
          ./MMoM_4.1.12 PTW-elev-00047.geo > ../outputs/PTW-elev-00047.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00047.geo'
          rm PTW-elev-00047.geo

echo ""
echo "time used to run PTW-elev-00047.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 48 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00048.geo .'
          cp ../inputs/PTW-elev-00048.geo .

sub_step './MMoM_4.1.12 PTW-elev-00048.geo > ../outputs/PTW-elev-00048.out'
          ./MMoM_4.1.12 PTW-elev-00048.geo > ../outputs/PTW-elev-00048.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00048.geo'
          rm PTW-elev-00048.geo

echo ""
echo "time used to run PTW-elev-00048.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 49 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00049.geo .'
          cp ../inputs/PTW-elev-00049.geo .

sub_step './MMoM_4.1.12 PTW-elev-00049.geo > ../outputs/PTW-elev-00049.out'
          ./MMoM_4.1.12 PTW-elev-00049.geo > ../outputs/PTW-elev-00049.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00049.geo'
          rm PTW-elev-00049.geo

echo ""
echo "time used to run PTW-elev-00049.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 50 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00050.geo .'
          cp ../inputs/PTW-elev-00050.geo .

sub_step './MMoM_4.1.12 PTW-elev-00050.geo > ../outputs/PTW-elev-00050.out'
          ./MMoM_4.1.12 PTW-elev-00050.geo > ../outputs/PTW-elev-00050.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00050.geo'
          rm PTW-elev-00050.geo

echo ""
echo "time used to run PTW-elev-00050.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 51 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00051.geo .'
          cp ../inputs/PTW-elev-00051.geo .

sub_step './MMoM_4.1.12 PTW-elev-00051.geo > ../outputs/PTW-elev-00051.out'
          ./MMoM_4.1.12 PTW-elev-00051.geo > ../outputs/PTW-elev-00051.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00051.geo'
          rm PTW-elev-00051.geo

echo ""
echo "time used to run PTW-elev-00051.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 52 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00052.geo .'
          cp ../inputs/PTW-elev-00052.geo .

sub_step './MMoM_4.1.12 PTW-elev-00052.geo > ../outputs/PTW-elev-00052.out'
          ./MMoM_4.1.12 PTW-elev-00052.geo > ../outputs/PTW-elev-00052.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00052.geo'
          rm PTW-elev-00052.geo

echo ""
echo "time used to run PTW-elev-00052.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 53 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00053.geo .'
          cp ../inputs/PTW-elev-00053.geo .

sub_step './MMoM_4.1.12 PTW-elev-00053.geo > ../outputs/PTW-elev-00053.out'
          ./MMoM_4.1.12 PTW-elev-00053.geo > ../outputs/PTW-elev-00053.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00053.geo'
          rm PTW-elev-00053.geo

echo ""
echo "time used to run PTW-elev-00053.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 54 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00054.geo .'
          cp ../inputs/PTW-elev-00054.geo .

sub_step './MMoM_4.1.12 PTW-elev-00054.geo > ../outputs/PTW-elev-00054.out'
          ./MMoM_4.1.12 PTW-elev-00054.geo > ../outputs/PTW-elev-00054.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00054.geo'
          rm PTW-elev-00054.geo

echo ""
echo "time used to run PTW-elev-00054.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 55 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00055.geo .'
          cp ../inputs/PTW-elev-00055.geo .

sub_step './MMoM_4.1.12 PTW-elev-00055.geo > ../outputs/PTW-elev-00055.out'
          ./MMoM_4.1.12 PTW-elev-00055.geo > ../outputs/PTW-elev-00055.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00055.geo'
          rm PTW-elev-00055.geo

echo ""
echo "time used to run PTW-elev-00055.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 56 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00056.geo .'
          cp ../inputs/PTW-elev-00056.geo .

sub_step './MMoM_4.1.12 PTW-elev-00056.geo > ../outputs/PTW-elev-00056.out'
          ./MMoM_4.1.12 PTW-elev-00056.geo > ../outputs/PTW-elev-00056.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00056.geo'
          rm PTW-elev-00056.geo

echo ""
echo "time used to run PTW-elev-00056.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 57 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00057.geo .'
          cp ../inputs/PTW-elev-00057.geo .

sub_step './MMoM_4.1.12 PTW-elev-00057.geo > ../outputs/PTW-elev-00057.out'
          ./MMoM_4.1.12 PTW-elev-00057.geo > ../outputs/PTW-elev-00057.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00057.geo'
          rm PTW-elev-00057.geo

echo ""
echo "time used to run PTW-elev-00057.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 58 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00058.geo .'
          cp ../inputs/PTW-elev-00058.geo .

sub_step './MMoM_4.1.12 PTW-elev-00058.geo > ../outputs/PTW-elev-00058.out'
          ./MMoM_4.1.12 PTW-elev-00058.geo > ../outputs/PTW-elev-00058.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00058.geo'
          rm PTW-elev-00058.geo

echo ""
echo "time used to run PTW-elev-00058.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 59 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00059.geo .'
          cp ../inputs/PTW-elev-00059.geo .

sub_step './MMoM_4.1.12 PTW-elev-00059.geo > ../outputs/PTW-elev-00059.out'
          ./MMoM_4.1.12 PTW-elev-00059.geo > ../outputs/PTW-elev-00059.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00059.geo'
          rm PTW-elev-00059.geo

echo ""
echo "time used to run PTW-elev-00059.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 60 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00060.geo .'
          cp ../inputs/PTW-elev-00060.geo .

sub_step './MMoM_4.1.12 PTW-elev-00060.geo > ../outputs/PTW-elev-00060.out'
          ./MMoM_4.1.12 PTW-elev-00060.geo > ../outputs/PTW-elev-00060.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00060.geo'
          rm PTW-elev-00060.geo

echo ""
echo "time used to run PTW-elev-00060.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 61 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00061.geo .'
          cp ../inputs/PTW-elev-00061.geo .

sub_step './MMoM_4.1.12 PTW-elev-00061.geo > ../outputs/PTW-elev-00061.out'
          ./MMoM_4.1.12 PTW-elev-00061.geo > ../outputs/PTW-elev-00061.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00061.geo'
          rm PTW-elev-00061.geo

echo ""
echo "time used to run PTW-elev-00061.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 62 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00062.geo .'
          cp ../inputs/PTW-elev-00062.geo .

sub_step './MMoM_4.1.12 PTW-elev-00062.geo > ../outputs/PTW-elev-00062.out'
          ./MMoM_4.1.12 PTW-elev-00062.geo > ../outputs/PTW-elev-00062.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00062.geo'
          rm PTW-elev-00062.geo

echo ""
echo "time used to run PTW-elev-00062.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 63 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00063.geo .'
          cp ../inputs/PTW-elev-00063.geo .

sub_step './MMoM_4.1.12 PTW-elev-00063.geo > ../outputs/PTW-elev-00063.out'
          ./MMoM_4.1.12 PTW-elev-00063.geo > ../outputs/PTW-elev-00063.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00063.geo'
          rm PTW-elev-00063.geo

echo ""
echo "time used to run PTW-elev-00063.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 64 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00064.geo .'
          cp ../inputs/PTW-elev-00064.geo .

sub_step './MMoM_4.1.12 PTW-elev-00064.geo > ../outputs/PTW-elev-00064.out'
          ./MMoM_4.1.12 PTW-elev-00064.geo > ../outputs/PTW-elev-00064.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00064.geo'
          rm PTW-elev-00064.geo

echo ""
echo "time used to run PTW-elev-00064.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 65 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00065.geo .'
          cp ../inputs/PTW-elev-00065.geo .

sub_step './MMoM_4.1.12 PTW-elev-00065.geo > ../outputs/PTW-elev-00065.out'
          ./MMoM_4.1.12 PTW-elev-00065.geo > ../outputs/PTW-elev-00065.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00065.geo'
          rm PTW-elev-00065.geo

echo ""
echo "time used to run PTW-elev-00065.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 66 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00066.geo .'
          cp ../inputs/PTW-elev-00066.geo .

sub_step './MMoM_4.1.12 PTW-elev-00066.geo > ../outputs/PTW-elev-00066.out'
          ./MMoM_4.1.12 PTW-elev-00066.geo > ../outputs/PTW-elev-00066.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00066.geo'
          rm PTW-elev-00066.geo

echo ""
echo "time used to run PTW-elev-00066.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 67 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00067.geo .'
          cp ../inputs/PTW-elev-00067.geo .

sub_step './MMoM_4.1.12 PTW-elev-00067.geo > ../outputs/PTW-elev-00067.out'
          ./MMoM_4.1.12 PTW-elev-00067.geo > ../outputs/PTW-elev-00067.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00067.geo'
          rm PTW-elev-00067.geo

echo ""
echo "time used to run PTW-elev-00067.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 68 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00068.geo .'
          cp ../inputs/PTW-elev-00068.geo .

sub_step './MMoM_4.1.12 PTW-elev-00068.geo > ../outputs/PTW-elev-00068.out'
          ./MMoM_4.1.12 PTW-elev-00068.geo > ../outputs/PTW-elev-00068.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00068.geo'
          rm PTW-elev-00068.geo

echo ""
echo "time used to run PTW-elev-00068.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 69 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00069.geo .'
          cp ../inputs/PTW-elev-00069.geo .

sub_step './MMoM_4.1.12 PTW-elev-00069.geo > ../outputs/PTW-elev-00069.out'
          ./MMoM_4.1.12 PTW-elev-00069.geo > ../outputs/PTW-elev-00069.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00069.geo'
          rm PTW-elev-00069.geo

echo ""
echo "time used to run PTW-elev-00069.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 70 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00070.geo .'
          cp ../inputs/PTW-elev-00070.geo .

sub_step './MMoM_4.1.12 PTW-elev-00070.geo > ../outputs/PTW-elev-00070.out'
          ./MMoM_4.1.12 PTW-elev-00070.geo > ../outputs/PTW-elev-00070.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00070.geo'
          rm PTW-elev-00070.geo

echo ""
echo "time used to run PTW-elev-00070.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 71 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00071.geo .'
          cp ../inputs/PTW-elev-00071.geo .

sub_step './MMoM_4.1.12 PTW-elev-00071.geo > ../outputs/PTW-elev-00071.out'
          ./MMoM_4.1.12 PTW-elev-00071.geo > ../outputs/PTW-elev-00071.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00071.geo'
          rm PTW-elev-00071.geo

echo ""
echo "time used to run PTW-elev-00071.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 72 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00072.geo .'
          cp ../inputs/PTW-elev-00072.geo .

sub_step './MMoM_4.1.12 PTW-elev-00072.geo > ../outputs/PTW-elev-00072.out'
          ./MMoM_4.1.12 PTW-elev-00072.geo > ../outputs/PTW-elev-00072.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00072.geo'
          rm PTW-elev-00072.geo

echo ""
echo "time used to run PTW-elev-00072.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 73 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00073.geo .'
          cp ../inputs/PTW-elev-00073.geo .

sub_step './MMoM_4.1.12 PTW-elev-00073.geo > ../outputs/PTW-elev-00073.out'
          ./MMoM_4.1.12 PTW-elev-00073.geo > ../outputs/PTW-elev-00073.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00073.geo'
          rm PTW-elev-00073.geo

echo ""
echo "time used to run PTW-elev-00073.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 74 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00074.geo .'
          cp ../inputs/PTW-elev-00074.geo .

sub_step './MMoM_4.1.12 PTW-elev-00074.geo > ../outputs/PTW-elev-00074.out'
          ./MMoM_4.1.12 PTW-elev-00074.geo > ../outputs/PTW-elev-00074.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00074.geo'
          rm PTW-elev-00074.geo

echo ""
echo "time used to run PTW-elev-00074.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 75 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00075.geo .'
          cp ../inputs/PTW-elev-00075.geo .

sub_step './MMoM_4.1.12 PTW-elev-00075.geo > ../outputs/PTW-elev-00075.out'
          ./MMoM_4.1.12 PTW-elev-00075.geo > ../outputs/PTW-elev-00075.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00075.geo'
          rm PTW-elev-00075.geo

echo ""
echo "time used to run PTW-elev-00075.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 76 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00076.geo .'
          cp ../inputs/PTW-elev-00076.geo .

sub_step './MMoM_4.1.12 PTW-elev-00076.geo > ../outputs/PTW-elev-00076.out'
          ./MMoM_4.1.12 PTW-elev-00076.geo > ../outputs/PTW-elev-00076.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00076.geo'
          rm PTW-elev-00076.geo

echo ""
echo "time used to run PTW-elev-00076.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 77 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00077.geo .'
          cp ../inputs/PTW-elev-00077.geo .

sub_step './MMoM_4.1.12 PTW-elev-00077.geo > ../outputs/PTW-elev-00077.out'
          ./MMoM_4.1.12 PTW-elev-00077.geo > ../outputs/PTW-elev-00077.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00077.geo'
          rm PTW-elev-00077.geo

echo ""
echo "time used to run PTW-elev-00077.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 78 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00078.geo .'
          cp ../inputs/PTW-elev-00078.geo .

sub_step './MMoM_4.1.12 PTW-elev-00078.geo > ../outputs/PTW-elev-00078.out'
          ./MMoM_4.1.12 PTW-elev-00078.geo > ../outputs/PTW-elev-00078.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00078.geo'
          rm PTW-elev-00078.geo

echo ""
echo "time used to run PTW-elev-00078.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 79 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00079.geo .'
          cp ../inputs/PTW-elev-00079.geo .

sub_step './MMoM_4.1.12 PTW-elev-00079.geo > ../outputs/PTW-elev-00079.out'
          ./MMoM_4.1.12 PTW-elev-00079.geo > ../outputs/PTW-elev-00079.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00079.geo'
          rm PTW-elev-00079.geo

echo ""
echo "time used to run PTW-elev-00079.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 80 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00080.geo .'
          cp ../inputs/PTW-elev-00080.geo .

sub_step './MMoM_4.1.12 PTW-elev-00080.geo > ../outputs/PTW-elev-00080.out'
          ./MMoM_4.1.12 PTW-elev-00080.geo > ../outputs/PTW-elev-00080.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00080.geo'
          rm PTW-elev-00080.geo

echo ""
echo "time used to run PTW-elev-00080.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 81 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00081.geo .'
          cp ../inputs/PTW-elev-00081.geo .

sub_step './MMoM_4.1.12 PTW-elev-00081.geo > ../outputs/PTW-elev-00081.out'
          ./MMoM_4.1.12 PTW-elev-00081.geo > ../outputs/PTW-elev-00081.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00081.geo'
          rm PTW-elev-00081.geo

echo ""
echo "time used to run PTW-elev-00081.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 82 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00082.geo .'
          cp ../inputs/PTW-elev-00082.geo .

sub_step './MMoM_4.1.12 PTW-elev-00082.geo > ../outputs/PTW-elev-00082.out'
          ./MMoM_4.1.12 PTW-elev-00082.geo > ../outputs/PTW-elev-00082.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00082.geo'
          rm PTW-elev-00082.geo

echo ""
echo "time used to run PTW-elev-00082.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 83 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00083.geo .'
          cp ../inputs/PTW-elev-00083.geo .

sub_step './MMoM_4.1.12 PTW-elev-00083.geo > ../outputs/PTW-elev-00083.out'
          ./MMoM_4.1.12 PTW-elev-00083.geo > ../outputs/PTW-elev-00083.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00083.geo'
          rm PTW-elev-00083.geo

echo ""
echo "time used to run PTW-elev-00083.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 84 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00084.geo .'
          cp ../inputs/PTW-elev-00084.geo .

sub_step './MMoM_4.1.12 PTW-elev-00084.geo > ../outputs/PTW-elev-00084.out'
          ./MMoM_4.1.12 PTW-elev-00084.geo > ../outputs/PTW-elev-00084.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00084.geo'
          rm PTW-elev-00084.geo

echo ""
echo "time used to run PTW-elev-00084.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 85 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00085.geo .'
          cp ../inputs/PTW-elev-00085.geo .

sub_step './MMoM_4.1.12 PTW-elev-00085.geo > ../outputs/PTW-elev-00085.out'
          ./MMoM_4.1.12 PTW-elev-00085.geo > ../outputs/PTW-elev-00085.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00085.geo'
          rm PTW-elev-00085.geo

echo ""
echo "time used to run PTW-elev-00085.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 86 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00086.geo .'
          cp ../inputs/PTW-elev-00086.geo .

sub_step './MMoM_4.1.12 PTW-elev-00086.geo > ../outputs/PTW-elev-00086.out'
          ./MMoM_4.1.12 PTW-elev-00086.geo > ../outputs/PTW-elev-00086.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00086.geo'
          rm PTW-elev-00086.geo

echo ""
echo "time used to run PTW-elev-00086.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 87 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00087.geo .'
          cp ../inputs/PTW-elev-00087.geo .

sub_step './MMoM_4.1.12 PTW-elev-00087.geo > ../outputs/PTW-elev-00087.out'
          ./MMoM_4.1.12 PTW-elev-00087.geo > ../outputs/PTW-elev-00087.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00087.geo'
          rm PTW-elev-00087.geo

echo ""
echo "time used to run PTW-elev-00087.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 88 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00088.geo .'
          cp ../inputs/PTW-elev-00088.geo .

sub_step './MMoM_4.1.12 PTW-elev-00088.geo > ../outputs/PTW-elev-00088.out'
          ./MMoM_4.1.12 PTW-elev-00088.geo > ../outputs/PTW-elev-00088.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00088.geo'
          rm PTW-elev-00088.geo

echo ""
echo "time used to run PTW-elev-00088.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 89 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00089.geo .'
          cp ../inputs/PTW-elev-00089.geo .

sub_step './MMoM_4.1.12 PTW-elev-00089.geo > ../outputs/PTW-elev-00089.out'
          ./MMoM_4.1.12 PTW-elev-00089.geo > ../outputs/PTW-elev-00089.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00089.geo'
          rm PTW-elev-00089.geo

echo ""
echo "time used to run PTW-elev-00089.geo = $((SECONDS-ticks)) s"

export ticks=${SECONDS}
new_step 'elevation angle = 90 deg from North Pole'

sub_step 'cp ../inputs/PTW-elev-00090.geo .'
          cp ../inputs/PTW-elev-00090.geo .

sub_step './MMoM_4.1.12 PTW-elev-00090.geo > ../outputs/PTW-elev-00090.out'
          ./MMoM_4.1.12 PTW-elev-00090.geo > ../outputs/PTW-elev-00090.out

sub_step 'mv *.4112.* ../outputs/.'
          mv *.4112.* ../outputs/.

sub_step 'rm PTW-elev-00090.geo'
          rm PTW-elev-00090.geo

echo ""
echo "time used to run PTW-elev-00090.geo = $((SECONDS-ticks)) s"

new_step 'clear shared files'
sub_step 'rm PTW-Materials.lib'
          rm PTW-Materials.lib
sub_step 'rm PTW.facet'
          rm PTW.facet
sub_step 'rm -r tempDir/'
          rm -r tempDir/

echo ""
echo "time used = ${SECONDS} s"
date

